[project]
name = "cpu"
version = "0.0.1-pre"
authors = []

[dependencies.bitflags]
git = "https://github.com/RustOS-Fork-Holding-Ground/bitflags"
branch = "rustos"

[dependencies.core]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust"
branch = "rustos"
